spring:
  application:
    name: project
  datasource:
    url: jdbc:mysql://localhost:3306/study
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: update
        default_batch_fetch_size: 1000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher # Swagger 3.x와 Spring Boot 2.6+ 호환 문제 해결

springdoc:
  swagger-ui:
    path: /swagger-ui.html # Swagger UI 접근 경로 설정
    enabled: true
  api-docs:
    enabled: true # API 문서 활성화
    path: /v3/api-docs # Swagger 문서의 기본 경로
  paths-to-match: /** # 모든 API 경로 매칭
  groups:
    enabled: true # 그룹화 설정 활성화